## Do not edit this file in_place 
## Copy to $HOME and modify values there 

export jupyter_hub_subscription_id=""
export jupyter_hub_tenant_id=""
export jupyter_hub_client_id=""
export jupyter_hub_resource_group_name="" 
export jupyter_hub_host=""

